### ISSUE TITLE
Any plans for update

### ISSUE THREAD

**Issue by ishubham-k** [hunterpayne/clifford_ref#1]
I was looking for a geometric algebra library for scala,  stumbled upon clifford_ref. Read me says that you are working on a more typesafe efficient lib. Are you going to publish it anytime soon ?

**Comment by hunterpayne** [comment]
I had been working on it but when I tried to generate all the dimensional types for given geometry it limited the library to a very small number of dimensions.  I'm using shapeless's dependent integer types to make the return types for each calculation (ie so the type system knows the difference between a vector and a bivector) and that proved too challenging for the Scala compiler in most use cases.  I'm also not sure it helps generate more efficient code as its still doing all the calculations on the CPU.

I'm not sure if I will be able to create the kind of library you are looking for or if I'm even on the right track to do that.  I'm hoping that the 2.13 or later Scala compilers will have improvements that remove some of these problems and allow me to make progress but I'm not optimistic about that.

If you are really interested in performance, perhaps a CUDA version of a GA library is more appropriate for what you want.  I'm don't believe I've seen that tried though.

**Comment by ishubham-k** [comment]
Thanks for the insights. I will close this issue then.
